server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: project-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/projects/**

        - id: execution-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/execute/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
