server:
  port: ${PORT:8082}

spring:
  datasource:
    url: jdbc:mysql://rapidrun-auth-rapid-run.c.aivencloud.com:19462/rapidrun_projects?useSSL=true&requireSSL=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${jwtSecret}