server:
  port: 8081


spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/rapidrun_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${userdb}
    password: ${passdb}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

url: jdbc:mysql://rapidrun-auth-rapid-run.c.aivencloud.com:19462/rapidrun_auth?ssl-mode=REQUIRED&useSSL=true&requireSSL=true
username: ${aivenname}
password: ${aivenpass}

jwt:
  secret: ${jwtSecret}
  expiration: 86400000

logging:
  level:
    com.rapidrun: DEBUG
